[package]
name = "mail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
imap = "2.4.1"
native-tls = "0.2.10"
quoted_printable = "0.4.5"
regex = "1.5.5"
